from abstraccion import *
cartas = [
    Leyenda("Valeria la Justiciera", 6, 7, 5, "Luz"),
    Leyenda("Kael'thas el Piromante", 9, 4, 7, "Fuego"),
    Leyenda("Liriel la Hechicera", 5, 8, 6, "Agua"),
    Leyenda("Tharok el Despiadado", 7, 6, 6, "Tierra"),
    Leyenda("Elyndra la Bendita", 6, 9, 7, "Luz"),
    Leyenda("Zarathos el Caótico", 8, 5, 6, "Fuego"),
    Leyenda("Seraphine la Celestial", 5, 10, 8, "Luz"),
    Leyenda("Grommash el Indomable", 9, 7, 8, "Tierra"),
    Leyenda("Nimue la Encantadora", 4, 6, 5, "Agua"),
    Leyenda("Draven el Gladiador", 8, 5, 6, "Fuego"),
    Leyenda("Morgana la Maldita", 7, 8, 7, "Oscuridad"),
    Leyenda("Altharion el Sabio", 5, 9, 7, "Luz"),
    Leyenda("Ragnar el Desolador", 10, 6, 9, "Fuego"),
    Leyenda("Luna la Cazadora", 6, 7, 6, "Luz"),
    Leyenda("Malakar el Sombrio", 7, 6, 6, "Oscuridad"),
    Leyenda("Eldrin el Arquimago", 5, 8, 7, "Agua"),
    Leyenda("Sylas el Rebelde", 8, 5, 6, "Tierra"),
    Leyenda("Isolde la Valiente", 6, 9, 7, "Luz"),
    Leyenda("Vortigern el Traidor", 7, 7, 7, "Oscuridad"),
    Leyenda("Aria la Cantora", 4, 6, 5, "Agua"),
    Leyenda("Karthus el Necrófago", 9, 5, 8, "Oscuridad"),
    Leyenda("Leona la Aurora", 6, 8, 7, "Luz"),
    Leyenda("Zephyr el Veloz", 7, 6, 6, "Viento"),
    Leyenda("Thalassa la Profunda", 5, 9, 7, "Agua"),
    Leyenda("Darius el Conquistador", 8, 6, 7, "Tierra"),
    Leyenda("Lyra la Estelar", 6, 7, 6, "Luz"),
    Leyenda("Mordekai el Verdugo", 9, 5, 8, "Oscuridad"),
    Leyenda("Elara la Eterna", 5, 10, 9, "Luz"),
    Leyenda("Gideon el Hechicero", 7, 6, 6, "Fuego"),
    Leyenda("Nyx la Sombría", 6, 7, 6, "Oscuridad"),
    Leyenda("Orion el Cazador", 8, 5, 6, "Viento"),
    
    ]
print(cartas.nombre)